### ISSUE TITLE
 Unable to load DLL 'Fuse.Text-PInvoke.dll'

### ISSUE THREAD

**Issue by Jean-Regis** [fuse-open/uno#221]
On a brand new computer, and after installing fuse (`npm install -g fuse-sdk` ...) we cannot run a dotnet build.

`uno build --run`

```
Error: System.DllNotFoundException: Unable to load DLL 'Fuse.Text-PInvoke.dll': Le module spÚcifiÚ est introuvable. (Exception from HRESULT: 0x8007007E)
   at Fuse.Text.Implementation.FreeType.Init_FreeType(IntPtr& library)
   at Fuse.Text.Implementation.FreeType.Init() in C:\Users\jeanr\AppData\Roaming\npm\node_modules\fuse-sdk\node_modules\@fuse-open\fuselibs\Source\build\Fuse.Text\1.12.0\Implementation\FreeType.uno:line 62
   at Fuse.Text.Implementation.FreeType.get_Library() in C:\Users\jeanr\AppData\Roaming\npm\node_modules\fuse-sdk\node_modules\@fuse-open\fuselibs\Source\build\Fuse.Text\1.12.0\Implementation\FreeType.uno:line 54
   at Fuse.Text.Implementation.FreeType.New_Memory_Face(Byte[] buffer, Int32 index, IntPtr& face) in C:\Users\jeanr\AppData\Roaming\npm\node_modules\fuse-sdk\node_modules\@fuse-open\fuselibs\Source\build\Fuse.Text\1.12.0\Implementation\FreeType.uno:line 85
[...]
```

It can compile, just crashes when running.

Works fine on android.

The dll is present in the  `C:\Users\[user]\AppData\Roaming\npm\node_modules\fuse-sdk\node_modules\@fuse-open\fuselibs\Source\build\Fuse.Text\1.12.0\harfbuzz\lib\Windows\x64` folder

Any help would be appreciated.

**Comment by mortend** [comment]
You probably need to install VC++ redistributables.

* 2010: https://www.microsoft.com/en-US/Download/confirmation.aspx?id=14632
* 2013: https://www.microsoft.com/en-gb/download/details.aspx?id=40784

**Comment by Jean-Regis** [comment]
Installed 2013. No change
Installed 2010. Worked !

May be wise to add this tidbit somewhere :-)

Thanks @mortend

**Comment by kusma** [comment]
I believe this is already documented here: https://github.com/fuse-open/fuselibs/blob/master/README.md#windows
